# Generated by Django 5.2.8 on 2025-11-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_parceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='mensagem',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
