# Generated by Django 5.2.8 on 2025-11-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_voluntario_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='cnpj',
            field=models.CharField(default='00000000000000', max_length=18),
            preserve_default=False,
        ),
    ]
