# Generated by Django 5.2.8 on 2025-11-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_alter_parceiro_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
    ]
